// buckets
export const ActionTypes = {
    FETCH_BUCKETS:"FETCH_BUCKETS",
    SELECTED_BUCKET:"SELECTED_BUCKET",
    REMOVE_SELECTED_BUCKET:"REMOVE_SELECTED_BUCKET",
    DELETE_BUCKET:"DELETE_BUCKET",
    EDIT_BUCKET:"EDIT_BUCKET",
    ADD_BUCKET:"ADD_BUCKET"
} 